# -*- coding: utf-8 -*-
"""Diwali Sales Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3mGxmwUsTOvWAXZeZfmbwoODHFHmWHT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Diwali Sales Data.csv',encoding = 'unicode_escape')

df.shape

df.head(15)

"""***Data Cleaning***"""

df.info()
# in this info we will see we have 2 blank columns so we have to drop them

# Drop Blank Columns
df.drop(['Status', 'unnamed1'], axis = 1 , inplace  = True)

# To Check Null Values
pd.isnull(df).sum()

# To Drop Null Values
df.dropna(inplace = True)

# To correct values in Marital_Status column
df['Marital_Status'] = df['Marital_Status'].replace({0:'Married',1:'Single'})

# To Change Data Type of 'Amount' to int
df['Amount'] = df['Amount'].astype('int')

df.columns

# To Change Column Name
df.rename(columns = {'Cust_name':'Customer_Name'},inplace = True)

# To get Basic Descibtion of numeric Columns
df[['Age','Orders','Amount']].describe()

"""***Data Filtering***"""

# Number of Customer as per Zone
df['Zone'].value_counts()

# Top 10 Purchase by amount
df.sort_values(by = 'Amount' , ascending = False).head(10)

# list of purchase where number of order is above 3
df[df['Orders']>3]

"""***(EDA) Exploratory Data Analysis***"""

plt.figure(figsize=(5, 5))
xa = sns.countplot(x='Gender', data=df)
for bars in xa.containers:
    xa.bar_label(bars)
plt.show()

# Sales amount by gender
plt.figure(figsize=(5, 5))
sales_gen = df.groupby(['Gender'] , as_index = False)['Amount'].sum().sort_values( by = 'Amount' , ascending = False)

sns.barplot(x = 'Gender', y = 'Amount' , data = sales_gen)

"""***Conclusion: From above Graphs we can see that most of the buyers are females and even Spendings of females are greater then men***

***Age***
"""

# Customers by Age Group and Gender
ax = sns.countplot(data = df, x = "Age Group", hue = 'Gender')

for bars in ax.containers:
    ax.bar_label(bars)

# Total sales amount by Age Group
sales_age = df.groupby(['Age Group'] , as_index = False)['Amount'].sum().sort_values( by = 'Amount' , ascending = False)

sns.barplot(x = 'Age Group', y = 'Amount' , data = sales_age)

"""***Conclusion: From above Graphs we can see that most of the buyers are from age group 26-35 and are females***

***State***
"""

# Top 10 State as Number of Orders
sales_state = df.groupby(['State'] , as_index = False)['Orders'].sum().sort_values( by = 'Orders' , ascending = False).head(10)

sns.set(rc={'figure.figsize':(18,3)})

sns.barplot(x = 'State', y = 'Orders' , data = sales_state)

# Top 10 State as per Sum of sales
sales_state = df.groupby(['State'] , as_index = False)['Amount'].sum().sort_values( by = 'Amount' , ascending = False).head(10)

sns.set(rc={'figure.figsize':(18,3)})

sns.barplot(x = 'State', y = 'Amount' , data = sales_state)

"""***Conclusion: From above graphs we can see that most of the orders and total sales amount is from uttar pradesh, maharashtra, karnataka respectively***

***Marital Status***
"""

# Number of customers as per marital status
xa = sns.countplot(data = df , x = 'Marital_Status')

sns.set(rc={'figure.figsize':(3,2)})

for bars in xa.containers:
    xa.bar_label(bars)

# Total sales as per marital status and gender
sales_ms = df.groupby(['Marital_Status','Gender'], as_index = False)['Amount'].sum().sort_values(by = 'Amount' ,ascending = False)

sns.set(rc= {'figure.figsize':(6,4)})

sns.barplot(x = 'Marital_Status', y = 'Amount', data = sales_ms, hue = 'Gender')

"""Most of the buyers are Married womens and they also contributes to highest amounts of sales

***Occupation***
"""

# Number of customer as per Occupation
sns.set(rc={'figure.figsize':(22,5)})

ax = sns.countplot(x = 'Occupation', data = df)

for bars in ax.containers:
    ax.bar_label(bars)

# Total sales amoont as per customer occupation
sales_occu = df.groupby(['Occupation'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False)

sns.set(rc={'figure.figsize':(22,5)})

sns.barplot(x = 'Occupation' , y = 'Amount' , data = sales_occu)

"""***Conclusion: Here we see that most of they buyers are working in IT, Healthcare and Aviation sector***

***Product_Category***
"""

# Count of customer as per Product category
plt.figure(figsize=(30, 5))
ax = sns.countplot(x = 'Product_Category', data = df,)

for bars in ax.containers:
    ax.bar_label(bars)

# Top 10 Product category as per sales amount
sales_Pc = df.groupby(['Product_Category'], as_index = False)['Amount'].sum().sort_values(by = 'Amount', ascending = False).head(10)

sns.set(rc={'figure.figsize':(22,5)})

sns.barplot(x = 'Product_Category' , y = 'Amount' , data = sales_Pc)

"""***Conclusion: From they above graphs we can see that most of the sold products are from food, clothing and electronics category***

***Short Conclusion: Married Women from age-group of 26-25 yrs from UP, Maharashtra and Karnataka working in IT, Healthcare and Aviation are more likely to buy products from Food, Clothing adn electronics category***
"""